### PR TITLE
Fixing a bug where uSync isn't able to sync fields of type Umbraco.DropDown or Umbraco.CheckBoxList

### PR DESCRIPTION
**Pull request by mikekberg**
We've been using your uSync content edition to sync some of our environments and we hit an issue, it looks like any field with a type of Umbraco.CheckBoxList or Umbraco.DropDown doesn't get imported.

Looking into the issue it looks like uSync is setting the property to the text value of the selected items but with DropDowns and Checkbox lists umbraco requires you to lookup the Id's and insert the values as a comma delimited list of ID's and not a comma delimited list of values.

This is the changes we've made to get uSync to work.

### CODE REVIEW

**Comment by maarten-kieft** [comment]
We having the same issue, what is the status of this merge request. Why isn't it merged after 3 years?

**Comment by KevinJump** [comment]
Hi,

this version of Content Edition was superseded by uSync v3.x  (which is currently v4.0.5) - the methods using for syncing differ quite a bit from between versions. 

this is one of those annoying things that has been fixed and the broken again at least once :( - but there are issues in the latest version of uSync looking at this - infact there is one due in the latest release that may actually fix this (not going to say for good). 

https://github.com/KevinJump/uSync/issues/175
https://github.com/KevinJump/uSync/issues/176

if you are already running the latest v of usync then updating the uSync.Core dependency to 6.0.6 will actually give you the two fixes above. 

https://www.nuget.org/packages/uSync.Core/6.0.6


I haven't merged this PR as the old version of the code and isn't actively supported, I don't currently have the time to go back and test / release this version - the latest v of usync supports all Umbraco Releases since Sept 2015.

**Comment by maarten-kieft** [comment]
thanks for your reply kevin, much appreciated. Maybe closing the mr as depreciated version an idea? since it wasnt clear that this code was for outdated version. anyway I will look into your sugesstion. And once again thanks for replying, I can imagine that you're really busy

**Comment by KevinJump** [comment]
yeah - github recently (as in the last year or so) made it so you can archive a whole repo - so i might do that.

**Pull request closed without merging**
